import type { Service } from "@/types/service";

export const SERVICES: Service[] = [
  {
    id: "ho-hap",
    title: "Hô hấp",
    description: "Khám và điều trị các bệnh lý đường hô hấp thường gặp ở trẻ em.",
    introduction: "Các bệnh đường hô hấp rất phổ biến ở trẻ nhỏ và có thể tiến triển nhanh. Trẻ được thăm khám toàn diện, đánh giá nhịp thở, nghe phổi và tư vấn chăm sóc phù hợp với độ tuổi.",
    commonConditions: ["Ho, sổ mũi, nghẹt mũi", "Viêm họng, viêm amidan", "Viêm phế quản, viêm tiểu phế quản", "Khò khè, hen phế quản", "Theo dõi viêm phổi sau điều trị"],
    examinationSteps: ["Trao đổi triệu chứng và tiền sử bệnh", "Khám tai mũi họng, đo dấu hiệu sinh tồn và nghe tim phổi", "Chỉ định xét nghiệm hoặc chẩn đoán hình ảnh khi cần", "Tư vấn điều trị và dấu hiệu cần tái khám"],
    parentNotes: ["Ghi lại thời điểm trẻ bắt đầu ho, sốt hoặc khó thở", "Mang theo đơn thuốc và kết quả khám gần nhất", "Đưa trẻ đi khám ngay khi thở rút lõm ngực, tím tái hoặc li bì"],
    icon: "lungs",
    featured: true,
    size: "large",
  },
  {
    id: "tieu-hoa",
    title: "Tiêu hóa",
    description: "Tư vấn và điều trị rối loạn tiêu hóa, đau bụng, tiêu chảy và táo bón ở trẻ.",
    introduction: "Rối loạn tiêu hóa ảnh hưởng trực tiếp đến ăn uống và tăng trưởng của trẻ. Việc thăm khám giúp xác định nguyên nhân, tránh tự dùng thuốc và xây dựng chế độ ăn phù hợp.",
    commonConditions: ["Đau bụng, đầy hơi, khó tiêu", "Nôn ói hoặc trào ngược", "Tiêu chảy cấp và kéo dài", "Táo bón, đi tiêu đau", "Biếng ăn liên quan đến tiêu hóa"],
    examinationSteps: ["Đánh giá chế độ ăn và thói quen đi tiêu", "Khám bụng và kiểm tra tình trạng mất nước", "Cân nhắc xét nghiệm khi có dấu hiệu bất thường", "Lập kế hoạch điều trị, dinh dưỡng và theo dõi"],
    parentNotes: ["Theo dõi số lần nôn hoặc đi tiêu trong ngày", "Chụp lại hình ảnh phân bất thường nếu thuận tiện", "Khám sớm khi trẻ nôn xanh, đi ngoài ra máu hoặc đau bụng dữ dội"],
    icon: "nutrition",
    size: "medium",
  },
  {
    id: "da-lieu",
    title: "Da liễu",
    description: "Thăm khám các vấn đề về da thường gặp ở trẻ sơ sinh và trẻ nhỏ.",
    introduction: "Da trẻ nhạy cảm và biểu hiện của nhiều bệnh có thể khá giống nhau. Bác sĩ đánh giá tổn thương da, yếu tố tiếp xúc và cơ địa để hướng dẫn chăm sóc an toàn.",
    commonConditions: ["Viêm da cơ địa, chàm sữa", "Rôm sảy, hăm tã", "Mề đay, phát ban", "Nhiễm khuẩn hoặc nhiễm nấm da", "Côn trùng cắn và phản ứng tại chỗ"],
    examinationSteps: ["Hỏi về thời điểm xuất hiện và yếu tố tiếp xúc", "Quan sát vị trí, hình thái và mức độ tổn thương", "Đánh giá dấu hiệu nhiễm trùng hoặc dị ứng", "Hướng dẫn dùng thuốc và chăm sóc da tại nhà"],
    parentNotes: ["Không bôi thêm sản phẩm mới trước buổi khám", "Mang theo các thuốc hoặc mỹ phẩm trẻ đang dùng", "Khám ngay nếu phát ban kèm khó thở, sưng môi mắt hoặc sốt cao"],
    icon: "stethoscope",
    size: "medium",
  },
  {
    id: "di-ung",
    title: "Dị ứng",
    description: "Chẩn đoán, tư vấn và điều trị các biểu hiện dị ứng ở trẻ em.",
    introduction: "Dị ứng có thể liên quan đến thức ăn, thuốc, môi trường hoặc cơ địa. Khai thác kỹ hoàn cảnh xuất hiện triệu chứng giúp xác định tác nhân nghi ngờ và phòng ngừa tái diễn.",
    commonConditions: ["Dị ứng thức ăn", "Viêm mũi dị ứng", "Mề đay, phù mạch", "Dị ứng thuốc nghi ngờ", "Khò khè liên quan đến dị ứng"],
    examinationSteps: ["Khai thác tác nhân và thời gian xuất hiện triệu chứng", "Đánh giá da, hô hấp và tiêu hóa", "Chỉ định kiểm tra chuyên sâu khi phù hợp", "Lập kế hoạch tránh tác nhân và xử trí khi tái phát"],
    parentNotes: ["Ghi lại thức ăn, thuốc hoặc môi trường trước phản ứng", "Không tự cho trẻ thử lại tác nhân nghi ngờ", "Gọi cấp cứu khi trẻ khó thở, khàn tiếng, choáng hoặc sưng nhanh"],
    icon: "vaccine",
    size: "small",
  },
  {
    id: "tai-mui-hong",
    title: "Tai Mũi Họng",
    description: "Khám và điều trị các bệnh lý tai, mũi, họng thường gặp ở trẻ.",
    introduction: "Các bệnh tai mũi họng thường tái diễn ở trẻ và có thể ảnh hưởng đến giấc ngủ, thính lực hoặc ăn uống. Khám đúng thời điểm giúp phát hiện biến chứng sớm.",
    commonConditions: ["Viêm tai giữa, đau tai", "Viêm mũi họng", "Amidan hoặc VA", "Chảy mũi kéo dài", "Ngáy và thở miệng khi ngủ"],
    examinationSteps: ["Trao đổi diễn tiến bệnh và số lần tái phát", "Khám tai, mũi, họng", "Đánh giá hô hấp và dấu hiệu biến chứng", "Tư vấn điều trị, vệ sinh mũi và lịch tái khám"],
    parentNotes: ["Không tự ngoáy tai hoặc nhỏ thuốc chưa được chỉ định", "Mang theo kết quả đo thính lực nếu có", "Khám sớm khi đau tai dữ dội, chảy mủ tai hoặc nghe kém đột ngột"],
    icon: "stethoscope",
    size: "small",
  },
  {
    id: "dinh-duong",
    title: "Dinh dưỡng",
    description: "Đánh giá tăng trưởng và tư vấn chế độ dinh dưỡng phù hợp theo độ tuổi.",
    introduction: "Dinh dưỡng cần được cá thể hóa theo tuổi, tốc độ tăng trưởng và tình trạng sức khỏe. Bác sĩ đánh giá biểu đồ tăng trưởng để cùng gia đình xây dựng kế hoạch thực tế.",
    commonConditions: ["Chậm tăng cân hoặc suy dinh dưỡng", "Thừa cân, béo phì", "Biếng ăn", "Thiếu vi chất nghi ngờ", "Tư vấn ăn dặm và khẩu phần theo tuổi"],
    examinationSteps: ["Đo cân nặng, chiều cao và đánh giá biểu đồ tăng trưởng", "Phân tích khẩu phần và thói quen ăn uống", "Tìm các nguyên nhân bệnh lý nếu có", "Xây dựng mục tiêu và kế hoạch dinh dưỡng theo dõi được"],
    parentNotes: ["Ghi nhật ký ăn uống của trẻ trong 2–3 ngày", "Mang theo sổ theo dõi cân nặng, chiều cao", "Không tự bổ sung vitamin hoặc thuốc kích thích ăn kéo dài"],
    icon: "growth",
    size: "wide",
  },
];
