import type { Service } from "@/types/service";

export const SERVICES: Service[] = [
  {
    id: "ho-hap",
    title: "Hô hấp",
    description: "Khám và điều trị các bệnh lý đường hô hấp thường gặp ở trẻ em.",
    introduction: "Các bệnh đường hô hấp rất phổ biến ở trẻ nhỏ và có thể tiến triển nhanh. Trẻ được thăm khám toàn diện, đánh giá nhịp thở, nghe phổi và tư vấn chăm sóc phù hợp với độ tuổi.",
    commonConditions: ["Ho, sổ mũi, nghẹt mũi", "Viêm họng, viêm amidan", "Viêm phế quản, viêm tiểu phế quản", "Khò khè, hen phế quản", "Theo dõi viêm phổi sau điều trị"],
    whenToVisit: ["Ho hoặc sốt kéo dài trên 2–3 ngày", "Trẻ khò khè, thở nhanh hoặc bú kém", "Bệnh hô hấp tái đi tái lại nhiều lần"],
    parentNotes: ["Ghi lại thời điểm trẻ bắt đầu ho, sốt hoặc khó thở", "Mang theo đơn thuốc và kết quả khám gần nhất", "Đưa trẻ đi khám ngay khi thở rút lõm ngực, tím tái hoặc li bì"],
    faqs: [{ question: "Trẻ ho có nhất thiết phải dùng kháng sinh?", answer: "Không. Phần lớn nhiễm trùng hô hấp ở trẻ do virus. Bác sĩ chỉ cân nhắc kháng sinh khi có bằng chứng hoặc nguy cơ nhiễm khuẩn." }, { question: "Có cần chụp X-quang mỗi khi trẻ ho?", answer: "Không thường quy. Việc chụp phim chỉ được cân nhắc khi khám lâm sàng gợi ý viêm phổi, biến chứng hoặc diễn tiến bất thường." }],
    icon: "lungs",
    size: "large",
  },
  {
    id: "tieu-hoa",
    title: "Tiêu hóa",
    description: "Tư vấn và điều trị rối loạn tiêu hóa, đau bụng, tiêu chảy và táo bón ở trẻ.",
    introduction: "Rối loạn tiêu hóa ảnh hưởng trực tiếp đến ăn uống và tăng trưởng của trẻ. Việc thăm khám giúp xác định nguyên nhân, tránh tự dùng thuốc và xây dựng chế độ ăn phù hợp.",
    commonConditions: ["Đau bụng, đầy hơi, khó tiêu", "Nôn ói hoặc trào ngược", "Tiêu chảy cấp và kéo dài", "Táo bón, đi tiêu đau", "Biếng ăn liên quan đến tiêu hóa"],
    whenToVisit: ["Đau bụng hoặc nôn ói tái diễn", "Tiêu chảy quá 24 giờ ở trẻ nhỏ", "Táo bón kéo dài, ảnh hưởng ăn ngủ"],
    parentNotes: ["Theo dõi số lần nôn hoặc đi tiêu trong ngày", "Chụp lại hình ảnh phân bất thường nếu thuận tiện", "Khám sớm khi trẻ nôn xanh, đi ngoài ra máu hoặc đau bụng dữ dội"],
    faqs: [{ question: "Trẻ tiêu chảy nên kiêng ăn không?", answer: "Không nên nhịn ăn. Trẻ cần tiếp tục bú hoặc ăn thức ăn phù hợp, dễ tiêu và được bù nước đúng cách theo hướng dẫn." }, { question: "Táo bón bao lâu thì cần đi khám?", answer: "Nên khám khi tình trạng kéo dài, trẻ đau hoặc sợ đi tiêu, có máu trong phân, chậm tăng cân hay các biện pháp sinh hoạt không cải thiện." }],
    icon: "nutrition",
    size: "medium",
  },
  {
    id: "da-lieu",
    title: "Da liễu",
    description: "Thăm khám các vấn đề về da thường gặp ở trẻ sơ sinh và trẻ nhỏ.",
    introduction: "Da trẻ nhạy cảm và biểu hiện của nhiều bệnh có thể khá giống nhau. Bác sĩ đánh giá tổn thương da, yếu tố tiếp xúc và cơ địa để hướng dẫn chăm sóc an toàn.",
    commonConditions: ["Viêm da cơ địa, chàm sữa", "Rôm sảy, hăm tã", "Mề đay, phát ban", "Nhiễm khuẩn hoặc nhiễm nấm da", "Côn trùng cắn và phản ứng tại chỗ"],
    whenToVisit: ["Tổn thương lan rộng hoặc ngứa nhiều", "Phát ban không rõ nguyên nhân", "Da rỉ dịch, đóng mủ hoặc tái phát"],
    parentNotes: ["Không bôi thêm sản phẩm mới trước buổi khám", "Mang theo các thuốc hoặc mỹ phẩm trẻ đang dùng", "Khám ngay nếu phát ban kèm khó thở, sưng môi mắt hoặc sốt cao"],
    faqs: [{ question: "Chàm sữa có tự hết không?", answer: "Nhiều trẻ cải thiện theo tuổi nhưng vẫn cần chăm sóc hàng rào da và kiểm soát đợt viêm để giảm ngứa, nhiễm trùng và tái phát." }, { question: "Có nên tự mua kem pha để bôi?", answer: "Không nên. Kem không rõ thành phần có thể chứa corticoid mạnh hoặc chất gây kích ứng, làm tổn thương da trẻ nếu dùng sai." }],
    icon: "stethoscope",
    size: "medium",
  },
  {
    id: "di-ung",
    title: "Dị ứng",
    description: "Chẩn đoán, tư vấn và điều trị các biểu hiện dị ứng ở trẻ em.",
    introduction: "Dị ứng có thể liên quan đến thức ăn, thuốc, môi trường hoặc cơ địa. Khai thác kỹ hoàn cảnh xuất hiện triệu chứng giúp xác định tác nhân nghi ngờ và phòng ngừa tái diễn.",
    commonConditions: ["Dị ứng thức ăn", "Viêm mũi dị ứng", "Mề đay, phù mạch", "Dị ứng thuốc nghi ngờ", "Khò khè liên quan đến dị ứng"],
    whenToVisit: ["Mề đay hoặc ngứa tái diễn", "Nghẹt mũi kéo dài ảnh hưởng giấc ngủ", "Nghi ngờ phản ứng với thức ăn hoặc thuốc"],
    parentNotes: ["Ghi lại thức ăn, thuốc hoặc môi trường trước phản ứng", "Không tự cho trẻ thử lại tác nhân nghi ngờ", "Gọi cấp cứu khi trẻ khó thở, khàn tiếng, choáng hoặc sưng nhanh"],
    faqs: [{ question: "Có cần kiêng tất cả thực phẩm dễ dị ứng?", answer: "Không. Kiêng khem rộng khi chưa có chẩn đoán có thể làm trẻ thiếu chất. Chỉ loại trừ tác nhân có cơ sở và theo kế hoạch của bác sĩ." }, { question: "Xét nghiệm dị ứng có xác định chắc chắn nguyên nhân?", answer: "Xét nghiệm cần được diễn giải cùng bệnh sử và triệu chứng. Kết quả dương tính đơn thuần chưa đồng nghĩa trẻ chắc chắn dị ứng với tác nhân đó." }],
    icon: "vaccine",
    size: "small",
  },
  {
    id: "tai-mui-hong",
    title: "Tai Mũi Họng",
    description: "Khám và điều trị các bệnh lý tai, mũi, họng thường gặp ở trẻ.",
    introduction: "Các bệnh tai mũi họng thường tái diễn ở trẻ và có thể ảnh hưởng đến giấc ngủ, thính lực hoặc ăn uống. Khám đúng thời điểm giúp phát hiện biến chứng sớm.",
    commonConditions: ["Viêm tai giữa, đau tai", "Viêm mũi họng", "Amidan hoặc VA", "Chảy mũi kéo dài", "Ngáy và thở miệng khi ngủ"],
    whenToVisit: ["Đau tai, kéo tai hoặc quấy khóc", "Chảy mũi kéo dài trên 10 ngày", "Ngáy, thở miệng thường xuyên khi ngủ"],
    parentNotes: ["Không tự ngoáy tai hoặc nhỏ thuốc chưa được chỉ định", "Mang theo kết quả đo thính lực nếu có", "Khám sớm khi đau tai dữ dội, chảy mủ tai hoặc nghe kém đột ngột"],
    faqs: [{ question: "Trẻ viêm tai giữa có luôn cần kháng sinh?", answer: "Không phải mọi trường hợp. Tuổi, mức độ đau, sốt và hình ảnh màng nhĩ sẽ quyết định theo dõi hay điều trị kháng sinh." }, { question: "Rửa mũi cho trẻ bao nhiêu lần một ngày?", answer: "Tần suất phụ thuộc tình trạng của trẻ. Thao tác nhẹ nhàng, đúng kỹ thuật quan trọng hơn việc rửa quá nhiều lần." }],
    icon: "stethoscope",
    size: "small",
  },
  {
    id: "dinh-duong",
    title: "Dinh dưỡng",
    description: "Đánh giá tăng trưởng và tư vấn chế độ dinh dưỡng phù hợp theo độ tuổi.",
    introduction: "Dinh dưỡng cần được cá thể hóa theo tuổi, tốc độ tăng trưởng và tình trạng sức khỏe. Bác sĩ đánh giá biểu đồ tăng trưởng để cùng gia đình xây dựng kế hoạch thực tế.",
    commonConditions: ["Chậm tăng cân hoặc suy dinh dưỡng", "Thừa cân, béo phì", "Biếng ăn", "Thiếu vi chất nghi ngờ", "Tư vấn ăn dặm và khẩu phần theo tuổi"],
    whenToVisit: ["Cân nặng đứng yên hoặc giảm", "Bữa ăn kéo dài, căng thẳng thường xuyên", "Cần xây dựng thực đơn ăn dặm phù hợp"],
    parentNotes: ["Ghi nhật ký ăn uống của trẻ trong 2–3 ngày", "Mang theo sổ theo dõi cân nặng, chiều cao", "Không tự bổ sung vitamin hoặc thuốc kích thích ăn kéo dài"],
    faqs: [{ question: "Có nên dùng thuốc kích thích ăn cho trẻ?", answer: "Không nên tự dùng. Biếng ăn cần tìm nguyên nhân và điều chỉnh cách ăn; một số sản phẩm có tác dụng phụ và không giải quyết gốc vấn đề." }, { question: "Một buổi tư vấn dinh dưỡng cần chuẩn bị gì?", answer: "Cha mẹ nên mang sổ theo dõi tăng trưởng, kết quả xét nghiệm nếu có và nhật ký ăn 2–3 ngày để bác sĩ đánh giá sát thực tế." }],
    icon: "growth",
    size: "wide",
  },
];
